name: Shell Scripts Unit Testing

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  testing_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.5
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Install Pytest dependencies
        run: |
          python -m pip install pytest
          python -m pip install -e {package_name}
      - name: Test with pytest
        run: |
          cd ./{package_name} #this may be needed if the package/package/test structure is used
          python -m pytest -vv -s